### PR TITLE
update icc sha256s

### PR DESCRIPTION
**Pull request by mo271**
https://github.com/libjxl/libjxl/pull/1744
changed the ICC profile for some files.

### CODE REVIEW

**Comment by mo271** [comment]
I'm not quite sure if the `reference.icc` also need to be changed, I just made the conformance tests pass..
Also I hope everything went alright with gsutils, I think it uploaded everything correctly...

**Comment by veluca93** [comment]
`reference.icc` does indeed not need to change.

I think we should not test the sha256 of the ICC generated out of enum-ColorEncoding at all though, every implementation is free to generate whatever equivalent profile they want there... @sboukortt opinions?

Could you check that the cases that were changed are all such that the jxl file contains an enum colorspace, and perhaps remove the icc sha check for those?

**Comment by szabadka** [comment]
I did not notice this PR, so I was changing it myself, but I only needed to change 18 files for the conformance test to pass, including one reference.icc

**Comment by veluca93** [comment]
> I did not notice this PR, so I was changing it myself, but I only needed to change 18 files for the conformance test to pass, including one reference.icc

Why would we need to change a reference.icc?

**Comment by szabadka** [comment]
Because there is a place where we check if reference icc is the same as decoded, and if not, we do color transform. But we cant do color transform between rgb and grayscale

**Comment by szabadka** [comment]
> I did not notice this PR, so I was changing it myself, but I only needed to change 18 files for the conformance test to pass, including one reference.icc

Ah, there are two more failures, so we probably need to update 3 reference iccs.

**Comment by veluca93** [comment]
> Because there is a place where we check if reference icc is the same as decoded, and if not, we do color transform. But we cant do color transform between rgb and grayscale

Ah, I see, then we should change the ICC, although at some point we should figure out how to make this work properly...

**Comment by mo271** [comment]
#26 is perhaps better?
I didn't see it before. Now I had remove the original.icc lines from json, don't know if this is what @veluca93 wanted.

**Pull request closed without merging**
